---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/auth/signin":
    post:
      summary: Signin
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: successful
        '403':
          description: wrong password
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
              required:
              - auth:
                - email
                - email
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
