import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import Login from '@/shared/components/login/login';
import Topbar from '@/shared/components/topbar/topbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Football Challenge</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Topbar />
        <Login />
      </main>
    </>
  );
}
