require 'swagger_helper'
# require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/v1/users', type: :request do
  fixtures :users

  let!(:fixture_user) do
    users(:one)
  end

  before(:each) do
    expect_any_instance_of(ApplicationController).to receive(:authorized?).and_return(nil)
  end

  path '/v1/users' do
    post('Create users') do
      tags 'Users'
      consumes 'application/json'
      produces 'application/json'
      parameter name: :user, in: :body, schema: {
        type: :object,
        properties: {
          user: {
            type: :object,
            properties: {
              name: { type: :string },
              email: { type: :string },
              password: { type: :string },
              role: { type: :integer }
            }
          }
        },
        required: [user: %w[name email password role]]
      }
      response(201, 'successful') do
        let(:user) { { user: { name: fixture_user.name, email: 'adminE@email.com', password: 'abc123', confirm_password: 'abc123',  role: fixture_user.role } } }
        run_test!
      end

      # response(401, 'wrong password') do
      #   let(:user) { { user: { player_id: 'admin@email.com', user_id: '123' } } }
      #   run_test! do |response|
      #     api_response = JSON.parse(response.body)
      #     expect(api_response['message']).equal?('Invalid password')
      #   end
      # end

      # response(404, 'user not found') do
      #   let(:user) { { user: { player_id: 'email@email.com', user_id: '123' } } }
      #   run_test! do |response|
      #     api_response = JSON.parse(response.body)
      #     expect(api_response['message']).equal?('User not Found')
      #   end
      # end
    end

    # get('List users') do
    #   tags 'Users'
    #   consumes 'application/json'
    #   produces 'application/json'

    #   response(200, 'successful') do
    #     run_test! do |response|
    #       api_response = JSON.parse(response.body)
    #       expect(api_response).to have_key('data')
    #     end
    #   end
    # end
  end

  path '/v1/users/{id}' do
    put('Update users') do
      tags 'Users'
      consumes 'application/json'
      produces 'application/json'
      parameter name: :id, in: :path, type: :string

      parameter name: :user, in: :body, schema: {
        type: :object,
        properties: {
          user: {
            type: :object,
            properties: {
              name: { type: :string },
              email: { type: :string },
              password: { type: :string },
              role: { type: :integer }
            }
          }
        },
        required: [user: %w[name email password role]]
      }
      response(200, 'successful') do
        let(:id) { fixture_user.id }
        let(:user) { { user: { name: fixture_user.name, email: 'adminEc@email.com', password: 'abc123', role: fixture_user.role } } }
        run_test!
      end
    end

    get('Show specific user') do
      tags 'Users'
      consumes 'application/json'
      produces 'application/json'
      parameter name: :id, in: :path, type: :string

      response '200', 'user found' do
        let(:id) { fixture_user.id }
        run_test!
      end
    end

    delete('Delete specific user') do
      tags 'Users'
      consumes 'application/json'
      produces 'application/json'
      parameter name: :id, in: :path, type: :integer

      response(204, 'successful') do
        let(:id) { fixture_user.id }
        run_test!
      end
    end
  end
end
